version: "3.1"

services:
  db:
    image: mongo:latest
    container_name: ${MONGO_SERVICE_NAME}
    restart: always
    volumes:
      - ./docker-volumes/highscoreData:/data/db
      - ./docker-volumes/config/001.mongo.init.js:/docker-entrypoint-initdb.d/001.mongo.init.js
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
      - MONGO_INITDB_DATABASE=${MONGO_DB}
    ports:
      - ${MONGO_PORT}:27017