version: "3.1"

services:
  db:
    image: mongo:latest
    container_name: ${MONGO_SERVICE_NAME}
    restart: always
    volumes:
      - ./docker-volumes/highscoreData:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
      - MONGO_INITDB_DATABASE=${MONGO_DB}
    ports:
      - ${MONGO_PORT}:27017
  mongo_admin:
    image: jeurboy/docker-phpmongoadmin
    container_name: phpmongoadmin
    restart: always
    ports:
      - 8080:80
    depends_on: 
      - db
    environment: 
      - MONGO_ADMIN_USERNAME=${MONGO_USER}
      - MONGO_ADMIN_PASSWORD=${MONGO_PASS}
      - MONGO_SERVER=db
      - MONGO_USERNAME=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASS}